"""Writes the data-source tables of docs/reproduce.md from data/registry.yaml, so that the
documentation cannot drift from the registry the pipeline reads.

    uv run --group pipeline python docs/tools/sources_table.py          # rewrite the tables
    uv run --group pipeline python docs/tools/sources_table.py --check  # exit 1 if out of date
"""

import hashlib
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
DOC = ROOT / "docs" / "reproduce.md"
BEGIN, END = "<!-- SOURCES:BEGIN (generated by docs/tools/sources_table.py) -->", "<!-- SOURCES:END -->"
TIER_ORDER = {"fit": 0, "dev": 1, "final": 2, "final-flagged": 3, "final-seen": 4, "bench": 5, "reserved": 6, "none": 7}


def table() -> str:
    reg = yaml.safe_load((ROOT / "data" / "registry.yaml").read_text(encoding="utf-8"))
    reg_sha = hashlib.sha256((ROOT / "data" / "registry.yaml").read_bytes()).hexdigest()
    manifest = json.loads((ROOT / "data" / "tiers" / "manifest.json").read_text(encoding="utf-8"))
    out = [f"Registry: `data/registry.yaml`, schema {reg['schema']}, licences checked "
           f"{reg['checked']}, SHA-256 `{reg_sha}`.", ""]
    if manifest.get("registry_sha256") != reg_sha:
        out += [f"> The tiers are built from registry SHA-256 `{manifest.get('registry_sha256')}`; "
                "the registry above differs from it in comments or notes only when "
                "`make verify-data` passes.", ""]
    for fmt in reg["formats"]:
        fams = reg["formats"][fmt]["families"]
        rows = []
        for key, s in reg["sources"].items():
            if s["format"] != fmt:
                continue
            tier = fams.get(s["family"], "none")
            if s.get("use") is False:
                tier = "not used"
            raw = reg["raw"].get(s.get("raw") or "", {})
            where = (f"[`{s['hub']}`](https://huggingface.co/datasets/{s['hub']})" if s.get("hub")
                     else "MultiVerS release (below)" if s.get("raw") == "multivers"
                     else f"[{raw['homepage'].removeprefix('https://')}]({raw['homepage']}) (below)" if raw
                     else "generated by `scripts/prep_tiers.py`")
            rev = (f"`{s['revision'][:12]}`" if s.get("revision")
                   else f"`{raw['commit'][:12]}`" if raw.get("commit") else "n/a")
            lic = ", ".join(s.get("licence", [])) or "n/a"
            cite = s.get("citation", "").replace("|", "/")
            rows.append((TIER_ORDER.get(tier, 5), key, f"| `{key}` | {s['family']} | {tier} | "
                         f"{where} | {rev} | {lic} | {cite} |"))
        rows.sort()
        out += [f"**{fmt}**", "",
                "| source | family | tier | where | revision | licence (as on the card) | citation |",
                "|---|---|---|---|---|---|---|"] + [r[2] for r in rows] + [""]
    mv = reg["raw"]["multivers"]
    out += [f"MultiVerS release: {mv['url']}, SHA-256 `{mv['sha256']}`, {mv['size']:,} bytes. "
            f"{mv['citation']}", "", "Other raw files (`make fetch`, SHA-256 checked):", "",
            "| file | URL | SHA-256 | bytes |", "|---|---|---|---|"]
    for name, raw in reg["raw"].items():
        for fname, f in (raw.get("files") or {}).items():
            out.append(f"| `data/raw/{name}/{fname}` | {f['url']} | `{f['sha256']}` | {f['size']:,} |")
    out += ["", "Built tiers (`data/tiers.sha256`, checked by `make verify-data`):", "",
            "| file | SHA-256 |", "|---|---|"]
    for line in (ROOT / "data" / "tiers.sha256").read_text().splitlines():
        sha, name = line.split()
        out.append(f"| `data/tiers/{name}` | `{sha}` |")
    return "\n".join(out)


def main() -> int:
    text = DOC.read_text(encoding="utf-8")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n{table()}\n{END}{tail}"
    if "--check" in sys.argv:
        if new != text:
            print("docs/reproduce.md: source tables out of date; run docs/tools/sources_table.py")
            return 1
        print("PASS source tables")
        return 0
    DOC.write_text(new, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
